### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by gusshawstewart** [githubschool/yeti#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by thibauldcroonenborghs-tomtom** [comment]
@gusshawstewart

**Comment by sebastianschrod-tomtom** [comment]
HI @gusshawstewart

**Comment by PatrickDelanghe-TomTom** [comment]
@gusshawstewart

**Comment by andrasbuettner-tomtom** [comment]
@gusshawstewart

**Comment by albertocortinas-tomtom** [comment]
@gusshawstewart

**Comment by sally0322** [comment]
@gusshawstewart

**Comment by FatimaRiconFerreira-TomTom** [comment]
@gusshawstewart
